### ISSUE TITLE
Python3 embeded python terminal

### ISSUE THREAD

**Issue by MaximilienNaveau** [stack-of-tasks/dynamic-graph-python#58]
I found a weird bug using the python3 embeded terminal and the dg_completer.
The interpreter get stuck upon `import readline` or `from rlcompleter import Completer`.

It is a shame as the completion is a huge bonus in the client terminal. 
This Issue is also in reference to the [dynamic-graph-bridge](https://github.com/stack-of-tasks/dynamic_graph_bridge/blob/master/src/dynamic_graph/ros/dgcompleter.py) python client of course.

Let me know if there is something I am missing.

Are you using the dynamic-graph-bridge already with python3?
If yes how do you do? (Maybe this question is for dynamic-graph-bridge)
I personnaly did a small C++ client using the ros-service and bound it pybind11.
So I can use ROS in python2 and 3 seemlessly.

**Comment by MaximilienNaveau** [comment]
I just wanted to mention the corresponding [dynamic-graph-brigde issue](https://github.com/stack-of-tasks/dynamic_graph_bridge/issues/75) related this.

**Comment by olivier-stasse** [comment]
Dear Maximilien,
I implemented but the rlcompleter but my impression that having the ipython kernel working would be simpler for us.
But this kernel is supported only using python3.
I am not up to date on this, so I let other people answer on this (maybe @nim65s who knows python3 more than me).
So I would be very happy to test your client, but I do think that when switching to python3 ipython might be come with interesting features than readline which might worth investigating.

**Comment by MaximilienNaveau** [comment]
I was wondering if we could the pybind11 embeded python terminal as well. I am not sure which one is the best...
I will investigate the possibility of the ipython terminal. Anyway if everything goes well in python3 I will definitely cut-off python 2 on my part.

**Comment by olivier-stasse** [comment]
@MaximilienNaveau I do not know pybind11. If you can make a comparison between the solutions, we are open to any solution which can improve the current status. Please be aware that there is an effort in switching to boost::python currently ported by @jmirabel

**Comment by nim65s** [comment]
pybind11 is just a modern boost::python without boost. There is no change in using one or the other, except:
- if you already have boost, you already have boost::python, so don't go for an additional dependency
- if you require C++ < 11, you can't use the modern pybind11.
- otherwise, pybind11 is a lighter dependency than boost.

But the API and functionnalities are the same.

**Comment by jmirabel** [comment]
> But the API and functionnalities are the same.

Although very similar, the two are still not the same in terms of API and ease of use. `pybind11` is definitely a lot easier to use not only because C++ 11 itself but because the API and function names are clearer than that of Boost Python. If you can choose, go for pybind11.

The only unclear part for me is the link between Eigen and NumPy. pybind11 provides a basic support for Eigen. I don't think it is as complete as eigenpy but I am not sure of this.

**Comment by MaximilienNaveau** [comment]
For pybind11 the eigen support is not too bad but induce a necessary copy of the data. Which might have been prevented in eigenpy (I do not know about this.).

Thanks for all the inputs. I would like to be on the same page as you guys for the python bindings as it make the code compatible through both institute. Clearly the current bindings and pybind11 are not compatible (I tried too pass a pinocchio.SE3 object to a C++ function binded with pybind11 and failed).

So if you guys say that you go for boost::python I should look into it and maybe provide tutorial for my team.

**Comment by jmirabel** [comment]
> Clearly the current bindings and pybind11 are not compatible (I tried too pass a pinocchio.SE3 object to a C++ function binded with pybind11 and failed).

It's not out of the box but it is doable.

**Comment by MaximilienNaveau** [comment]
If you have a guide on how-to I am interested!

**Comment by jmirabel** [comment]
No link. I came to that by trial and errors.

https://github.com/hungpham2511/toppra/blob/6e903f435d6a583aad731e67a4224fea7c830b27/cpp/bindings/constraints.cpp#L106 allows you to extract inside pybind11 an object exposed with boost python.

There is probably an automatic way of doing it by registration of a cast. It's a bit tricky because you have to go into the internals of boost python or pybind11. I haven't tried.

**Comment by MaximilienNaveau** [comment]
Ok that a very good help! I will probably try to do that and if the compatibility is doable and not too annoying then I will keep pybind11 as our main python bindings.
